#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba8, binding = 0) uniform image2D opaqueImage;
layout(r8, binding = 1) uniform image2D geometryAlphaImage;
layout(binding = 2) uniform sampler2D accumulationTex;
layout(binding = 3) uniform sampler2D revealageTex;

uniform vec3 backgroundColor;

void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 imageSize_ = imageSize(opaqueImage);
    
    if (texelCoord.x >= imageSize_.x || texelCoord.y >= imageSize_.y)
        return;
    
    vec2 uv = (vec2(texelCoord) + 0.5) / vec2(imageSize_);
    
    vec3 opaque = imageLoad(opaqueImage, texelCoord).rgb;
    float geometryAlpha = imageLoad(geometryAlphaImage, texelCoord).r;

    vec4 accumulation = texture(accumulationTex, uv);
    float revealage = min(texture(revealageTex, uv).r, 1.0);

    vec3 averageColorOfTranslucentGeometry = accumulation.rgb / max(accumulation.a, 1e-5);

    // Blend opaque over background (geometryAlpha is either 0 or 1)
    vec3 finalColor = mix(backgroundColor, opaque, geometryAlpha);
    
    // Blend transparent over opaque
    finalColor = mix(finalColor, averageColorOfTranslucentGeometry, revealage);
    float finalGeometryAlpha = geometryAlpha + revealage;

    imageStore(opaqueImage, texelCoord, vec4(finalColor, 1.0));
    imageStore(geometryAlphaImage, texelCoord, vec4(finalGeometryAlpha));
}