#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) restrict writeonly buffer noiseArraySSBO
{
	float noiseArray[];
};

uniform ivec2 resolution;
uniform vec2 offset;
uniform float step_;
uniform int seed;

uint cellHash(ivec2 p)
{
	uint h = 0xdeadbeefu;
    h ^= uint(p.x) + 0x9e3779b9u + (h << 6u) + (h >> 2u);
    h ^= uint(p.y) + 0x9e3779b9u + (h << 6u) + (h >> 2u);
    h ^= h >> 16u;
    h *= 0x85ebca6bu;
    h ^= h >> 13u;
    h *= 0xc2b2ae35u;
    h ^= h >> 16u;
    return h;
}

float grad(uint hash, vec2 p)
{
	switch (hash & 7)
        {
        case 0: return  p.x + p.y;  // 1, 1
        case 1: return -p.x + p.y;  //-1, 1
        case 2: return  p.x - p.y;  // 1,-1
        case 3: return -p.x - p.y;  //-1,-1
        case 4: return  p.x;		// 1, 0
        case 5: return -p.x;		//-1, 0
        case 6: return  p.y;		// 0, 1
        case 7: return -p.y;		// 0,-1
        }
}

vec2 fade(vec2 p)
{
	return p * p * p * (p * (p * 6.0 - 15.0) + 10.0);
}

float samplePerlinNoise(vec2 samplePoint)
{
	vec2 pFloored = floor(samplePoint);
	ivec2 cellPos = ivec2(pFloored);
	vec2 pFrac = samplePoint - pFloored;

	ivec2 c00 = cellPos;
    ivec2 c10 = ivec2(cellPos.x + 1, cellPos.y);
    ivec2 c01 = ivec2(cellPos.x,	 cellPos.y + 1);
    ivec2 c11 = ivec2(cellPos.x + 1, cellPos.y + 1);

	uint h00 = cellHash(c00) + seed;
	uint h10 = cellHash(c10) + seed;
	uint h01 = cellHash(c01) + seed;
	uint h11 = cellHash(c11) + seed;

	float n00 = grad(h00, pFrac);
	float n10 = grad(h10, pFrac - vec2(1, 0));
	float n01 = grad(h01, pFrac - vec2(0, 1));
	float n11 = grad(h11, pFrac - vec2(1, 1));

	vec2 pFade = fade(pFrac);

	float x0 = mix(n00, n10, pFade.x);
	float x1 = mix(n01, n11, pFade.x);
	return mix(x0, x1, pFade.y);
}

float generate(ivec2 pixel)
{
	vec2 baseScale = vec2(1.0) / (resolution * step_);
	vec2 samplePoint = (vec2(pixel) + offset) * step_;
	return samplePerlinNoise(samplePoint);
}

void main()
{
	// Get thread position
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

	// Ensure pixel is in boundaries
    if (pixel.x >= resolution.x || pixel.y >= resolution.y) return;

	// Sample noise
	float noise = float(pixel.x + pixel.y) / (resolution.x + resolution.y - 2);

	// Calculate pixel index
	int pixelIndex = pixel.y * resolution.x + pixel.x;

	// Write value to noise array
	noiseArray[pixelIndex] = noise;
}